name: eclipse_tz
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  build_runner: ^2.2.1
  dio: ^5.2.1+1
  shared_preferences: ^2.0.8
  get_it: ^7.2.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

